<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>PhoneDebug</AssemblyName>
    <RootNamespace>PhoneDebug.App</RootNamespace>
    <Description>Phone Debug for Windows.</Description>
    <ApplicationIcon>..\assets\phone-debug.ico</ApplicationIcon>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationVisualStyles>true</ApplicationVisualStyles>
    <ApplicationUseCompatibleTextRendering>false</ApplicationUseCompatibleTextRendering>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhoneDebug.Core\PhoneDebug.Core.csproj" />
  </ItemGroup>

</Project>
